// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropTrac_backend.Services.Context;

#nullable disable

namespace PropTrac_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240404204331_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AmenFeatList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Baths")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Expenses")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseOrRoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseRent")
                        .HasColumnType("int");

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int>("RoomRent")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("RoomInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.SecurityQuestionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SecurityQuestion");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Question = "What is your mother's maiden name?"
                        },
                        new
                        {
                            ID = 2,
                            Question = "What is the name of your first pet?"
                        },
                        new
                        {
                            ID = 3,
                            Question = "What was the name of your first stuffed animal?"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaseEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaseStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomInfoID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentID")
                        .IsUnique()
                        .HasFilter("[DocumentID] IS NOT NULL");

                    b.HasIndex("PropertyInfoID");

                    b.HasIndex("RoomInfoID")
                        .IsUnique()
                        .HasFilter("[RoomInfoID] IS NOT NULL");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("DaysRemaining")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentRecieved")
                        .HasColumnType("bit");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TenantID")
                        .IsUnique();

                    b.ToTable("TenantPaymentInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SecurityQuestionID");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Manager")
                        .HasForeignKey("PropTrac_backend.Models.ManagerModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany()
                        .HasForeignKey("PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.DocumentsModel", "Document")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "DocumentID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany()
                        .HasForeignKey("PropertyInfoID");

                    b.HasOne("PropTrac_backend.Models.RoomInfoModel", "RoomInfo")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "RoomInfoID");

                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("PropertyInfo");

                    b.Navigation("RoomInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.TenantModel", "Tenant")
                        .WithOne("TenantPaymentInfo")
                        .HasForeignKey("PropTrac_backend.Models.TenantPaymentInfoModel", "TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.SecurityQuestionModel", "SecurityQuestion")
                        .WithMany()
                        .HasForeignKey("SecurityQuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityQuestion");
                });

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Navigation("TenantPaymentInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Tenant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
