// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropTrac_backend.Services.Context;

#nullable disable

namespace PropTrac_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = new byte[] { 1, 2, 3 },
                            Name = "LeaseAgreement",
                            Type = "Lease",
                            UploadDate = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2281)
                        },
                        new
                        {
                            ID = 2,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "LeaseAgreement",
                            Type = "Lease",
                            UploadDate = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2286)
                        },
                        new
                        {
                            ID = 3,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "ManagerList",
                            Type = "Manager",
                            UploadDate = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2290)
                        },
                        new
                        {
                            ID = 4,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "ManagerDoc",
                            Type = "Finance",
                            UploadDate = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2293)
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.MaintenanceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Maintenance");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Plumbing",
                            ContractorEmail = "plumbing@example.com",
                            ContractorName = "Plumbing Pros",
                            ContractorPhone = "123-456-7890",
                            DateRequested = new DateTime(2024, 5, 23, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2352),
                            Description = "There's something wrong with the toilet.",
                            Priority = "Urgent",
                            Status = "To Do",
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            Category = "Electricity",
                            ContractorEmail = "electricity@example.com",
                            ContractorName = "Electricity Experts",
                            ContractorPhone = "987-654-3210",
                            DateRequested = new DateTime(2024, 5, 18, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2356),
                            Description = "Outlets aren't working",
                            Priority = "Standard",
                            Status = "In Progress",
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            Category = "HVAC",
                            ContractorEmail = "hvac@example.com",
                            ContractorName = "HVAC Solutions",
                            ContractorPhone = "555-555-5555",
                            DateRequested = new DateTime(2024, 5, 13, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2359),
                            Description = "not sure what's wrong",
                            Priority = "Standard",
                            Status = "Completed",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerDocumentsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DocumentsID")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentsID")
                        .IsUnique()
                        .HasFilter("[DocumentsID] IS NOT NULL");

                    b.HasIndex("ManagerID");

                    b.ToTable("ManagerDocuments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DocumentsID = 3,
                            ManagerID = 1
                        },
                        new
                        {
                            ID = 2,
                            DocumentsID = 4,
                            ManagerID = 1
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerFinanceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyRentRecieved")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID")
                        .IsUnique();

                    b.ToTable("ManagerFinance");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManagerID = 1,
                            MonthlyRentRecieved = 3000
                        },
                        new
                        {
                            ID = 2,
                            ManagerID = 2,
                            MonthlyRentRecieved = 2500
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "John",
                            Language = "English",
                            LastName = "Doe",
                            Location = "New York",
                            Phone = "123-456-7890",
                            Role = "Manager",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Jane",
                            Language = "Spanish",
                            LastName = "Smith",
                            Location = "Los Angeles",
                            Phone = "987-654-3210",
                            Role = "Manager",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerPropertiesModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("PropertyInfoID")
                        .IsUnique()
                        .HasFilter("[PropertyInfoID] IS NOT NULL");

                    b.ToTable("ManagerProperties");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManagerID = 1,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            ManagerID = 1,
                            PropertyInfoID = 2
                        },
                        new
                        {
                            ID = 3,
                            ManagerID = 2,
                            PropertyInfoID = 3
                        },
                        new
                        {
                            ID = 4,
                            ManagerID = 2,
                            PropertyInfoID = 4
                        },
                        new
                        {
                            ID = 5,
                            ManagerID = 1,
                            PropertyInfoID = 5
                        },
                        new
                        {
                            ID = 6,
                            ManagerID = 1,
                            PropertyInfoID = 6
                        },
                        new
                        {
                            ID = 7,
                            ManagerID = 1,
                            PropertyInfoID = 7
                        },
                        new
                        {
                            ID = 8,
                            ManagerID = 1,
                            PropertyInfoID = 8
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.ContractorModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contractor");
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.MonthlyPropertyFinanceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ExpenseAmount")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int>("RevenueAmount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID")
                        .IsUnique();

                    b.ToTable("MonthlyPropertyFinance");
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.PropertyExpenseModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFixedAmount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("PropertyExpense");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 300,
                            Date = new DateTime(2023, 11, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2109),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 300,
                            Date = new DateTime(2023, 12, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2113),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 3,
                            Amount = 300,
                            Date = new DateTime(2024, 1, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2115),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 4,
                            Amount = 300,
                            Date = new DateTime(2024, 2, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2117),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 5,
                            Amount = 300,
                            Date = new DateTime(2024, 3, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2119),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 6,
                            Amount = 300,
                            Date = new DateTime(2024, 4, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2121),
                            Description = "Mortgage",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 7,
                            Amount = 200,
                            Date = new DateTime(2024, 4, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2123),
                            Description = "Maintenance Repair",
                            IsFixedAmount = false,
                            IsRecurring = false,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 8,
                            Amount = 250,
                            Date = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2125),
                            Description = "Maintenance Repair",
                            IsFixedAmount = false,
                            IsRecurring = false,
                            PropertyInfoID = 1
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.PropertyRevenueModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFixedAmount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("PropertyRevenue");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 2000,
                            Date = new DateTime(2023, 11, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2149),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 2000,
                            Date = new DateTime(2023, 12, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2152),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 3,
                            Amount = 2000,
                            Date = new DateTime(2024, 1, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2154),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 4,
                            Amount = 2000,
                            Date = new DateTime(2024, 2, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2156),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 5,
                            Amount = 2000,
                            Date = new DateTime(2024, 3, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2158),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 6,
                            Amount = 2000,
                            Date = new DateTime(2024, 4, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2160),
                            Description = "Rent",
                            IsFixedAmount = true,
                            IsRecurring = true,
                            PropertyInfoID = 1
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AmenFeatList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Baths")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseOrRoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseRent")
                        .HasColumnType("int");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PropertyInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AmenFeatList = "Swimming Pool, Gym",
                            Baths = 2,
                            City = "Anytown",
                            Description = "Spacious family house",
                            HouseNumber = "123",
                            HouseOrRoomType = "House",
                            HouseRent = 2000,
                            Rooms = 3,
                            Sqft = 1800,
                            State = "CA",
                            Street = "Main St",
                            Zip = "12345"
                        },
                        new
                        {
                            ID = 2,
                            AmenFeatList = "Laundry, Parking, Backyard",
                            Baths = 1,
                            City = "Otherville",
                            Description = "Cozy condo with rooms for rent",
                            HouseNumber = "456",
                            HouseOrRoomType = "Rooms",
                            HouseRent = 1500,
                            Rooms = 2,
                            Sqft = 1000,
                            State = "NY",
                            Street = "Oak St",
                            Zip = "54321"
                        },
                        new
                        {
                            ID = 3,
                            AmenFeatList = "Garage, Patio",
                            Baths = 1,
                            City = "Smalltown",
                            Description = "Charming cottage",
                            HouseNumber = "789",
                            HouseOrRoomType = "House",
                            HouseRent = 1800,
                            Rooms = 2,
                            Sqft = 1200,
                            State = "TX",
                            Street = "Pine St",
                            Zip = "67890"
                        },
                        new
                        {
                            ID = 4,
                            AmenFeatList = "Utilities Included",
                            Baths = 1,
                            City = "Villageton",
                            Description = "Small home",
                            HouseNumber = "101",
                            HouseOrRoomType = "House",
                            HouseRent = 1200,
                            Rooms = 2,
                            Sqft = 800,
                            State = "FL",
                            Street = "Maple St",
                            Zip = "98765"
                        },
                        new
                        {
                            ID = 5,
                            AmenFeatList = "Fenced Yard, Fireplace",
                            Baths = 2,
                            City = "Hometown",
                            Description = "Classic single-family home",
                            HouseNumber = "222",
                            HouseOrRoomType = "House",
                            HouseRent = 2200,
                            Rooms = 3,
                            Sqft = 1700,
                            State = "CA",
                            Street = "Cedar St",
                            Zip = "54321"
                        },
                        new
                        {
                            ID = 6,
                            AmenFeatList = "Shared Kitchen, Pet Friendly",
                            Baths = 1,
                            City = "Homestead",
                            Description = "Roomy apartment for rent",
                            HouseNumber = "333",
                            HouseOrRoomType = "Rooms",
                            HouseRent = 1600,
                            Rooms = 2,
                            Sqft = 1100,
                            State = "NY",
                            Street = "Elm St",
                            Zip = "12345"
                        },
                        new
                        {
                            ID = 7,
                            AmenFeatList = "Furnished, Parking",
                            Baths = 1,
                            City = "Villageton",
                            Description = "Quaint cottage available",
                            HouseNumber = "444",
                            HouseOrRoomType = "House",
                            HouseRent = 1500,
                            Rooms = 2,
                            Sqft = 900,
                            State = "FL",
                            Street = "Birch St",
                            Zip = "98765"
                        },
                        new
                        {
                            ID = 8,
                            AmenFeatList = "Deck, Garden",
                            Baths = 2,
                            City = "Smalltown",
                            Description = "Lovely family home",
                            HouseNumber = "555",
                            HouseOrRoomType = "House",
                            HouseRent = 2000,
                            Rooms = 3,
                            Sqft = 1600,
                            State = "TX",
                            Street = "Willow St",
                            Zip = "67890"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyMaintenanceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MaintenanceID")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaintenanceID")
                        .IsUnique()
                        .HasFilter("[MaintenanceID] IS NOT NULL");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("PropertyMaintenance");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaintenanceID = 1,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            MaintenanceID = 2,
                            PropertyInfoID = 2
                        },
                        new
                        {
                            ID = 3,
                            MaintenanceID = 3,
                            PropertyInfoID = 1
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int>("RoomRent")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("RoomInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PropertyInfoID = 2,
                            RoomRent = 800
                        },
                        new
                        {
                            ID = 2,
                            PropertyInfoID = 2,
                            RoomRent = 700
                        },
                        new
                        {
                            ID = 3,
                            PropertyInfoID = 6,
                            RoomRent = 800
                        },
                        new
                        {
                            ID = 4,
                            PropertyInfoID = 6,
                            RoomRent = 800
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.SecurityQuestionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SecurityQuestion");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Question = "What is the name of your first pet?"
                        },
                        new
                        {
                            ID = 2,
                            Question = "What was your favorite teacher's name?"
                        },
                        new
                        {
                            ID = 3,
                            Question = "What was the name of your first stuffed animal?"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DocumentsID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaseEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaseStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomInfoID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentsID")
                        .IsUnique()
                        .HasFilter("[DocumentsID] IS NOT NULL");

                    b.HasIndex("PropertyInfoID");

                    b.HasIndex("RoomInfoID")
                        .IsUnique()
                        .HasFilter("[RoomInfoID] IS NOT NULL");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DocumentsID = 1,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            LeaseEnd = new DateTime(2025, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(1990),
                            LeaseStart = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(1926),
                            LeaseType = "Annual",
                            Phone = "123-456-7890",
                            PropertyInfoID = 1,
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DocumentsID = 2,
                            FirstName = "Bob",
                            LastName = "Williams",
                            LeaseEnd = new DateTime(2024, 6, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(1997),
                            LeaseStart = new DateTime(2024, 5, 28, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(1996),
                            LeaseType = "Monthly",
                            Phone = "987-654-3210",
                            PropertyInfoID = 2,
                            RoomInfoID = 1,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("DaysRemaining")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentRecieved")
                        .HasColumnType("bit");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TenantID")
                        .IsUnique();

                    b.ToTable("TenantPaymentInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Balance = 1000,
                            DaysRemaining = 7,
                            DueDate = new DateTime(2024, 6, 4, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2016),
                            PaymentRecieved = false,
                            TenantID = 1
                        },
                        new
                        {
                            ID = 2,
                            Balance = 1500,
                            DaysRemaining = 9,
                            DueDate = new DateTime(2024, 6, 6, 8, 21, 51, 462, DateTimeKind.Local).AddTicks(2022),
                            PaymentRecieved = false,
                            TenantID = 2
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswerHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswerSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecurityQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SecurityQuestionID");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john@example.com",
                            Hash = "AlLyHuvzRGu11h4/ORtCgZVKvO7DKT7Dtq8LuPhraAX7ao4H117p29pzS8wOfXBPp5EsHhlXnLC+kcOtMsaffSwAtLSMbhOtxsxbCBG7xGkLUlioZnpc4PkMSlDH3R4eeZ5sdEQMzsWkH+t95YVM8hDja5ea8+lS6trEDc3o+Q2bzz6YMYbTXpavpIuVEy09jCHXnl5VhvCKlxLtxCat6Hu/COibP9YaCXoEW147DODl9lwEvr4/ZsnWqe3nW4ig3gTlfcsr4JQmrXZbGndFwIsBjWFk2T852j785l0ivY2Y3WxzDn3HUjuJXol23/B7s5N/aoPexdZcTscj06SX9w==",
                            IsManager = true,
                            Salt = "dwUyT/7+S+Lx1/PK5fRWuB/gEmP85AckcliceYIzFphTuvHe/sT6aO7vSrVHeSEwCobcWPU50kyAd65fyacRnA==",
                            SecurityAnswerHash = "security_hash1",
                            SecurityAnswerSalt = "security_salt1",
                            SecurityQuestionID = 1,
                            Username = "john_doe"
                        },
                        new
                        {
                            ID = 2,
                            Email = "jane@example.com",
                            Hash = "hash2",
                            IsManager = true,
                            Salt = "salt2",
                            SecurityAnswerHash = "security_hash2",
                            SecurityAnswerSalt = "security_salt2",
                            SecurityQuestionID = 2,
                            Username = "jane_smith"
                        },
                        new
                        {
                            ID = 3,
                            Email = "alice@example.com",
                            Hash = "tJDTelPa0qGlm0RGu0qpnj+fZd4OiKgqNB43bYO9uCdf/BRgJDOdqs4YIZjfczvMx/zhLEHzM2P5NLGtGuNJ85rX56Yw73QcjkyrzdRGbg5Kwzo+5pNJ1KzbKfGryyHrmbcSWW4lADGI2qm3xTyJw8tH73Mupj8QfktM98RszKEmcAgTH4ywCtfhAOgc+aKM6/5YCdSEEyuOhPwefN/FQCNRU5hHhzNDAV7s3z9x/O7dW9ccBjtV+C1tS7VDOJ7b5su8cfd1ac+QfIfqDV4SFwmA1z0acoWSsls1dBkZeWDHPklyZm2oThPzyOCHBA4KBy7X6XccwuMoNT38m8vBFg==",
                            IsManager = false,
                            Salt = "+CXVrwchiAje4z5uWz5Qew8Zwl/AZDGLzUUpG/x4nchjbMqnOu8z0J3SNAX/wGSwMCso6HI3vJJMa3lRyzx9pA==",
                            SecurityAnswerHash = "security_hash3",
                            SecurityAnswerSalt = "security_salt3",
                            SecurityQuestionID = 3,
                            Username = "alice_johnson"
                        },
                        new
                        {
                            ID = 4,
                            Email = "bob@example.com",
                            Hash = "hash4",
                            IsManager = false,
                            Salt = "salt4",
                            SecurityAnswerHash = "security_hash4",
                            SecurityAnswerSalt = "security_salt4",
                            SecurityQuestionID = 1,
                            Username = "bob_williams"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerDocumentsModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.DocumentsModel", "Documents")
                        .WithOne("ManagerDocuments")
                        .HasForeignKey("PropTrac_backend.Models.ManagerDocumentsModel", "DocumentsID");

                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithMany("ManagerDocuments")
                        .HasForeignKey("ManagerID");

                    b.Navigation("Documents");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerFinanceModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithOne("ManagerFinance")
                        .HasForeignKey("PropTrac_backend.Models.ManagerFinanceModel", "ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Manager")
                        .HasForeignKey("PropTrac_backend.Models.ManagerModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerPropertiesModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithMany("ManagerProperties")
                        .HasForeignKey("ManagerID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithOne("ManagerProperties")
                        .HasForeignKey("PropTrac_backend.Models.ManagerPropertiesModel", "PropertyInfoID");

                    b.Navigation("Manager");

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.MonthlyPropertyFinanceModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithOne("MonthlyPropertyFinance")
                        .HasForeignKey("PropTrac_backend.Models.Property.MonthlyPropertyFinanceModel", "PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.PropertyExpenseModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("PropertyExpense")
                        .HasForeignKey("PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.Property.PropertyRevenueModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("PropertyRevenue")
                        .HasForeignKey("PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyMaintenanceModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.MaintenanceModel", "Maintenance")
                        .WithOne("PropertyMaintenance")
                        .HasForeignKey("PropTrac_backend.Models.PropertyMaintenanceModel", "MaintenanceID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("PropertyMaintenance")
                        .HasForeignKey("PropertyInfoID");

                    b.Navigation("Maintenance");

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("RoomInfo")
                        .HasForeignKey("PropertyInfoID");

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.DocumentsModel", "Documents")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "DocumentsID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("Tenant")
                        .HasForeignKey("PropertyInfoID");

                    b.HasOne("PropTrac_backend.Models.RoomInfoModel", "RoomInfo")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "RoomInfoID");

                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("PropertyInfo");

                    b.Navigation("RoomInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.TenantModel", "Tenant")
                        .WithOne("TenantPaymentInfo")
                        .HasForeignKey("PropTrac_backend.Models.TenantPaymentInfoModel", "TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.SecurityQuestionModel", "SecurityQuestion")
                        .WithMany()
                        .HasForeignKey("SecurityQuestionID");

                    b.Navigation("SecurityQuestion");
                });

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Navigation("ManagerDocuments");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.MaintenanceModel", b =>
                {
                    b.Navigation("PropertyMaintenance");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.Navigation("ManagerDocuments");

                    b.Navigation("ManagerFinance");

                    b.Navigation("ManagerProperties");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyInfoModel", b =>
                {
                    b.Navigation("ManagerProperties");

                    b.Navigation("MonthlyPropertyFinance");

                    b.Navigation("PropertyExpense");

                    b.Navigation("PropertyMaintenance");

                    b.Navigation("PropertyRevenue");

                    b.Navigation("RoomInfo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Navigation("TenantPaymentInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Tenant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
