// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropTrac_backend.Services.Context;

#nullable disable

namespace PropTrac_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = new byte[] { 1, 2, 3 },
                            Name = "LeaseAgreement",
                            Type = "Lease",
                            UploadDate = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(6131)
                        },
                        new
                        {
                            ID = 2,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "LeaseAgreement",
                            Type = "Lease",
                            UploadDate = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(6136)
                        },
                        new
                        {
                            ID = 3,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "ManagerList",
                            Type = "Manager",
                            UploadDate = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(6140)
                        },
                        new
                        {
                            ID = 4,
                            Content = new byte[] { 4, 5, 6 },
                            Name = "ManagerDoc",
                            Type = "Finance",
                            UploadDate = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(6144)
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerDocumentsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DocumentsID")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentsID")
                        .IsUnique()
                        .HasFilter("[DocumentsID] IS NOT NULL");

                    b.HasIndex("ManagerID");

                    b.ToTable("ManagerDocuments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DocumentsID = 3,
                            ManagerID = 1
                        },
                        new
                        {
                            ID = 2,
                            DocumentsID = 4,
                            ManagerID = 1
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerFinanceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyRentRecieved")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID")
                        .IsUnique();

                    b.ToTable("ManagerFinance");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManagerID = 1,
                            MonthlyRentRecieved = 3000
                        },
                        new
                        {
                            ID = 2,
                            ManagerID = 2,
                            MonthlyRentRecieved = 2500
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "John",
                            Language = "English",
                            LastName = "Doe",
                            Location = "New York",
                            Phone = "123-456-7890",
                            Role = "Manager",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Jane",
                            Language = "Spanish",
                            LastName = "Smith",
                            Location = "Los Angeles",
                            Phone = "987-654-3210",
                            Role = "Manager",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerPropertiesModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("PropertyInfoID")
                        .IsUnique()
                        .HasFilter("[PropertyInfoID] IS NOT NULL");

                    b.ToTable("ManagerProperties");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManagerID = 1,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            ManagerID = 1,
                            PropertyInfoID = 2
                        },
                        new
                        {
                            ID = 3,
                            ManagerID = 2,
                            PropertyInfoID = 3
                        },
                        new
                        {
                            ID = 4,
                            ManagerID = 2,
                            PropertyInfoID = 4
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyExpenseModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaintenceCosts")
                        .HasColumnType("int");

                    b.Property<int>("Mortage")
                        .HasColumnType("int");

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID")
                        .IsUnique();

                    b.ToTable("PropertyExpense");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaintenceCosts = 300,
                            Mortage = 1500,
                            PropertyInfoID = 1
                        },
                        new
                        {
                            ID = 2,
                            MaintenceCosts = 250,
                            Mortage = 1200,
                            PropertyInfoID = 2
                        },
                        new
                        {
                            ID = 3,
                            MaintenceCosts = 200,
                            Mortage = 1300,
                            PropertyInfoID = 3
                        },
                        new
                        {
                            ID = 4,
                            MaintenceCosts = 180,
                            Mortage = 1000,
                            PropertyInfoID = 4
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyIncomeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID")
                        .IsUnique();

                    b.ToTable("PropertyIncome");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PropertyInfoID = 1,
                            Rent = 2500
                        },
                        new
                        {
                            ID = 2,
                            PropertyInfoID = 2,
                            Rent = 1800
                        },
                        new
                        {
                            ID = 3,
                            PropertyInfoID = 3,
                            Rent = 2000
                        },
                        new
                        {
                            ID = 4,
                            PropertyInfoID = 4,
                            Rent = 1400
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AmenFeatList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Baths")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Expenses")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseOrRoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseRent")
                        .HasColumnType("int");

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PropertyInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AmenFeatList = "Swimming Pool, Gym",
                            Baths = 2,
                            City = "Anytown",
                            Description = "Spacious family house",
                            Expenses = 1800,
                            HouseNumber = "123",
                            HouseOrRoomType = "House",
                            HouseRent = 2000,
                            Income = 2500,
                            Rooms = 3,
                            Sqft = 1800,
                            State = "CA",
                            Street = "Main St",
                            Zip = "12345"
                        },
                        new
                        {
                            ID = 2,
                            AmenFeatList = "Laundry, Parking, Backyard",
                            Baths = 1,
                            City = "Otherville",
                            Description = "Cozy condo with rooms for rent",
                            Expenses = 1450,
                            HouseNumber = "456",
                            HouseOrRoomType = "Rooms",
                            HouseRent = 1500,
                            Income = 1800,
                            Rooms = 2,
                            Sqft = 1000,
                            State = "NY",
                            Street = "Oak St",
                            Zip = "54321"
                        },
                        new
                        {
                            ID = 3,
                            AmenFeatList = "Garage, Patio",
                            Baths = 1,
                            City = "Smalltown",
                            Description = "Charming cottage",
                            Expenses = 1500,
                            HouseNumber = "789",
                            HouseOrRoomType = "House",
                            HouseRent = 1800,
                            Income = 2000,
                            Rooms = 2,
                            Sqft = 1200,
                            State = "TX",
                            Street = "Pine St",
                            Zip = "67890"
                        },
                        new
                        {
                            ID = 4,
                            AmenFeatList = "Utilities Included",
                            Baths = 1,
                            City = "Villageton",
                            Description = "Small home",
                            Expenses = 1180,
                            HouseNumber = "101",
                            HouseOrRoomType = "House",
                            HouseRent = 1200,
                            Income = 1400,
                            Rooms = 2,
                            Sqft = 800,
                            State = "FL",
                            Street = "Maple St",
                            Zip = "98765"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int>("RoomRent")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropertyInfoID");

                    b.ToTable("RoomInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PropertyInfoID = 2,
                            RoomRent = 500
                        },
                        new
                        {
                            ID = 2,
                            PropertyInfoID = 2,
                            RoomRent = 600
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.SecurityQuestionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SecurityQuestion");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Question = "What is the name of your first pet?"
                        },
                        new
                        {
                            ID = 2,
                            Question = "What was your favorite teacher's name?"
                        },
                        new
                        {
                            ID = 3,
                            Question = "What was the name of your first stuffed animal?"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DocumentsID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaseEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaseStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomInfoID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentsID")
                        .IsUnique()
                        .HasFilter("[DocumentsID] IS NOT NULL");

                    b.HasIndex("PropertyInfoID");

                    b.HasIndex("RoomInfoID")
                        .IsUnique()
                        .HasFilter("[RoomInfoID] IS NOT NULL");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DocumentsID = 1,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            LeaseEnd = new DateTime(2025, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5930),
                            LeaseStart = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5885),
                            LeaseType = "Annual",
                            Phone = "123-456-7890",
                            PropertyInfoID = 1,
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DocumentsID = 2,
                            FirstName = "Bob",
                            LastName = "Williams",
                            LeaseEnd = new DateTime(2024, 5, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5940),
                            LeaseStart = new DateTime(2024, 4, 10, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5939),
                            LeaseType = "Monthly",
                            Phone = "987-654-3210",
                            PropertyInfoID = 2,
                            RoomInfoID = 1,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("DaysRemaining")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentRecieved")
                        .HasColumnType("bit");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TenantID")
                        .IsUnique();

                    b.ToTable("TenantPaymentInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Balance = 1000,
                            DaysRemaining = 7,
                            DueDate = new DateTime(2024, 4, 17, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5961),
                            PaymentRecieved = false,
                            TenantID = 1
                        },
                        new
                        {
                            ID = 2,
                            Balance = 1500,
                            DaysRemaining = 9,
                            DueDate = new DateTime(2024, 4, 19, 15, 26, 17, 780, DateTimeKind.Local).AddTicks(5966),
                            PaymentRecieved = false,
                            TenantID = 2
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswerHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswerSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SecurityQuestionID");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john@example.com",
                            Hash = "hash1",
                            IsManager = true,
                            Salt = "salt1",
                            SecurityAnswerHash = "security_hash1",
                            SecurityAnswerSalt = "security_salt1",
                            SecurityQuestionID = 1,
                            Username = "john_doe"
                        },
                        new
                        {
                            ID = 2,
                            Email = "jane@example.com",
                            Hash = "hash2",
                            IsManager = true,
                            Salt = "salt2",
                            SecurityAnswerHash = "security_hash2",
                            SecurityAnswerSalt = "security_salt2",
                            SecurityQuestionID = 2,
                            Username = "jane_smith"
                        },
                        new
                        {
                            ID = 3,
                            Email = "alice@example.com",
                            Hash = "hash3",
                            IsManager = false,
                            Salt = "salt3",
                            SecurityAnswerHash = "security_hash3",
                            SecurityAnswerSalt = "security_salt3",
                            SecurityQuestionID = 3,
                            Username = "alice_johnson"
                        },
                        new
                        {
                            ID = 4,
                            Email = "bob@example.com",
                            Hash = "hash4",
                            IsManager = false,
                            Salt = "salt4",
                            SecurityAnswerHash = "security_hash4",
                            SecurityAnswerSalt = "security_salt4",
                            SecurityQuestionID = 1,
                            Username = "bob_williams"
                        });
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerDocumentsModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.DocumentsModel", "Documents")
                        .WithOne("ManagerDocuments")
                        .HasForeignKey("PropTrac_backend.Models.ManagerDocumentsModel", "DocumentsID");

                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithMany("ManagerDocuments")
                        .HasForeignKey("ManagerID");

                    b.Navigation("Documents");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerFinanceModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithOne("ManagerFinance")
                        .HasForeignKey("PropTrac_backend.Models.ManagerFinanceModel", "ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Manager")
                        .HasForeignKey("PropTrac_backend.Models.ManagerModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerPropertiesModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.ManagerModel", "Manager")
                        .WithMany("ManagerProperties")
                        .HasForeignKey("ManagerID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithOne("ManagerProperties")
                        .HasForeignKey("PropTrac_backend.Models.ManagerPropertiesModel", "PropertyInfoID");

                    b.Navigation("Manager");

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyExpenseModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithOne("PropertyExpense")
                        .HasForeignKey("PropTrac_backend.Models.PropertyExpenseModel", "PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyIncomeModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithOne("PropertyIncome")
                        .HasForeignKey("PropTrac_backend.Models.PropertyIncomeModel", "PropertyInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("RoomInfo")
                        .HasForeignKey("PropertyInfoID");

                    b.Navigation("PropertyInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.DocumentsModel", "Documents")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "DocumentsID");

                    b.HasOne("PropTrac_backend.Models.PropertyInfoModel", "PropertyInfo")
                        .WithMany("Tenant")
                        .HasForeignKey("PropertyInfoID");

                    b.HasOne("PropTrac_backend.Models.RoomInfoModel", "RoomInfo")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "RoomInfoID");

                    b.HasOne("PropTrac_backend.Models.UserModel", "User")
                        .WithOne("Tenant")
                        .HasForeignKey("PropTrac_backend.Models.TenantModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("PropertyInfo");

                    b.Navigation("RoomInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantPaymentInfoModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.TenantModel", "Tenant")
                        .WithOne("TenantPaymentInfo")
                        .HasForeignKey("PropTrac_backend.Models.TenantPaymentInfoModel", "TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.HasOne("PropTrac_backend.Models.SecurityQuestionModel", "SecurityQuestion")
                        .WithMany()
                        .HasForeignKey("SecurityQuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityQuestion");
                });

            modelBuilder.Entity("PropTrac_backend.Models.DocumentsModel", b =>
                {
                    b.Navigation("ManagerDocuments");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.ManagerModel", b =>
                {
                    b.Navigation("ManagerDocuments");

                    b.Navigation("ManagerFinance");

                    b.Navigation("ManagerProperties");
                });

            modelBuilder.Entity("PropTrac_backend.Models.PropertyInfoModel", b =>
                {
                    b.Navigation("ManagerProperties");

                    b.Navigation("PropertyExpense");

                    b.Navigation("PropertyIncome");

                    b.Navigation("RoomInfo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.RoomInfoModel", b =>
                {
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropTrac_backend.Models.TenantModel", b =>
                {
                    b.Navigation("TenantPaymentInfo");
                });

            modelBuilder.Entity("PropTrac_backend.Models.UserModel", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Tenant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
